import React from "react";
import { Button, StyleSheet, Text, View, FlatList, RefreshControl, ActivityIndicator } from "react-native";
import {createAppContainer} from "react-navigation";
import {createMaterialTopTabNavigator} from "react-navigation-tabs";
import NavigationUtil from "../navigator/NavigationUtil";
import actions from "../action"
import { connect } from "react-redux";
import { onRefreshPopular } from "../action/popular";
import PopularItem from "../common/PopularItem";
import Toast, {DURATION} from 'react-native-easy-toast';
import NavigationBar from "../common/NavigationBar";

const URL = 'https://api.github.com/search/repositories?q='
const QUERY_STR = '&sort=stars';
const THEME_COLOR = '#678';
const pageSize = 10;

export default class PopularPage extends React.Component{
  constructor(props) {
    super(props);
    this.tabNames = ['python', 'js','go'];
  }

  _genTabs() {
    const tabs = {};
    this.tabNames.forEach((item, index)=>{
      tabs[`tab${index}`] = {
        screen: props => <PopularTabPage {...props} tabLabel={item}/>,
        navigationOptions: {
          tabBarLabel: item
        }
      }
    })
    return tabs;
  }

  render() {
    let statusBar = {
      backgroundColor: THEME_COLOR,
      barStyle: 'light-content'
    }
    let navigationBar = <NavigationBar
      title={'Hot'}
      statusBar={statusBar}
      style={{backgroundColor: THEME_COLOR}}
    />

    const TabNavigator = createAppContainer(createMaterialTopTabNavigator(
      this._genTabs(),{
        tabBarOptions: {
          tabStyle: styles.tabStyle,
          indicatorStyle: styles.indicatorStyle,
          upperCaseLabel: false,
          style: {
            backgroundColor: '#a67'
          },
          scrollEnabled: true,
          labelStyle: styles.labelStyle
        }
      }
    ))
    return (
      <View style={styles.container} >
        {navigationBar}
        <TabNavigator />
      </View>
    )
  }
}

class PopularTab extends React.Component {
  constructor(props) {
    super(props);
    const {tabLabel } = this.props;
    this.storeName = tabLabel;
    console.log('storeName:' + this.storeName);
  }

  componentDidMount() {
    this.loadData(false);
  }

  loadData(isLoadMore) {
    const {onRefreshPopular, onLoadMorePopular} = this.props;
    const store = this.getStore();

    if (isLoadMore) {
      console.log('store.items' + store.items);
      onLoadMorePopular(this.storeName, ++store.pageIndex, pageSize, store.items, (message)=>{
        this.refs.toast.show(message);
      });
    } else {

      console.log('store: ' + store);
      onRefreshPopular(this.storeName, this.getFetchURL(this.storeName), pageSize);
    }
  }

  getStore(){
    const {popular} = this.props;
    console.log("popular: " + popular);
    let store = popular[this.storeName];
    console.log("popular, this.storeName, store: " + popular + this.storeName + store);
    if (!store) {
      store = {
        items: [],
        projectModes: [],
        hideLoadingMore: true,
        isLoading: false,
      }
    }
    return store;
  }

  getFetchURL(key) {
    return URL + key + QUERY_STR;
  }

  renderItem(data) {
    const item = data.item;
    return (
      <PopularItem
        item={item}
        onSelect={()=> {

        }}
      />
    )
  }

  getIndicator(){
    return this.getStore().hideLoadingMore? null:
      (<View style={styles.indicatorContainer}>
        <ActivityIndicator style={styles.indicator}/>
        <Text>loading more</Text>
      </View>)
  }

  render() {
    const store = this.getStore();
    return (
      <View style={styles.container}>
        <FlatList data={store.projectModes}
                  renderItem={
                    // data is a object generated by flatlist, it wraps a single item of
                    // store.projectModes, you can access that wrapped item by data.item
                    data => this.renderItem(data)}
                  keyExtractor={item =>""+ item.id}
                  refreshControl={(
                    <RefreshControl
                      title ={'loading'}
                      titleColor={THEME_COLOR}
                      colors ={[THEME_COLOR]}
                      refreshing={store.isLoading}
                      onRefresh={() =>{
                        this.loadData(false);
                      }}
                      tintColor={THEME_COLOR}
                    />
                  )}
                  ListFooterComponent={() => this.getIndicator()}
                  onEndReached={()=>{
                    this.loadData(true);
                  }}

                  onEndReachedThreshold={0.5}
        />
        <Toast ref={'toast'}
               position={'center'}
        />
      </View>
    )
  }
}

const mapStateToProps = state => ({
  popular: state.Popular,
});
const mapDispatchToProps = dispatch => ({
  onRefreshPopular: (storeName, url, pageSize) => dispatch(actions.onRefreshPopular(storeName, url, pageSize)),
  onLoadMorePopular: (storeName, pageIndex, pageSize, dataArray, callBack) =>
dispatch(actions.onLoadMorePopular(storeName, pageIndex, pageSize, dataArray, callBack)),
});

const PopularTabPage = connect(mapStateToProps, mapDispatchToProps)(PopularTab);


const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10
  },
  tabStyle: {
    minWidth: 50,
  },
  indicatorStyle: {
    height: 2,
    backgroundColor: 'white'
  },
  labelStyle: {
    fontSize: 13,
    marginTop: 6,
    marginBottom: 6
  },
  indicatorContainer: {
    alignItems: 'center',
  },
  indicator: {
    margin: 10,
    color: 'red'
  }
})
